# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: F★ for the masses
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  News from the F★ team! This blog covers new language features, general discussions,
  theoretical roadblocks, engineering challenges, and pretty much the daily life
  of any language implementor.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fstarlang.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  fstarlang

# Build settings
markdown: kramdown
theme: minima
